export enum TaskType {
  LAUNCH_BROWSER = "LAUNCH_BROWSER",
  PAGE_TO_HTML = "PAGE_TO_HTML",
  EXTRACT_TEXT_FROM_ELEMENT = "EXTRACT_TEXT_FROM_ELEMENT",
  FILL_INPUT = "FILL_INPUT",
  CLICK_ELEMENT = "CLICK_ELEMENT",
  WAIT_FOR_ELEMENT = "WAIT_FOR_ELEMENT",
  DELIVER_VIA_WEBHOOK = "DELIVER_VIA_WEBHOOK",
  EXTRACT_DATA_WITH_AI = "EXTRACT_DATA_WITH_AI",
  READ_PROPERTY_FROM_JSON = "READ_PROPERTY_FROM_JSON",
  ADD_PROPERTY_TO_JSON = "ADD_PROPERTY_TO_JSON",
  NAVIGATE_URL = "NAVIGATE_URL",
  SCROLL_TO_ELEMENT = "SCROLL_TO_ELEMENT",
  TAKE_SCREENSHOT = "TAKE_SCREENSHOT",
  // Enhanced tasks
  WAIT_DELAY = "WAIT_DELAY",
  EXTRACT_TABLE_DATA = "EXTRACT_TABLE_DATA",
  CONDITIONAL_LOGIC = "CONDITIONAL_LOGIC",
  DATA_TRANSFORM = "DATA_TRANSFORM",
  DOWNLOAD_FILE = "DOWNLOAD_FILE",
  SEND_EMAIL = "SEND_EMAIL",
  LOOP = "LOOP",
  FILTER_DATA = "FILTER_DATA",
}

export enum TaskCategory {
  BROWSER = "BROWSER",
  INTERACTION = "INTERACTION",
  EXTRACTION = "EXTRACTION",
  STORAGE = "STORAGE",
  TIMING = "TIMING",
  DELIVERY = "DELIVERY",
  AI = "AI",
  ADVANCED = "ADVANCED",
  COMMUNICATION = "COMMUNICATION",
}

export enum TaskParamType {
  STRING = "STRING",
  BROWSER_INSTANCE = "BROWSER_INSTANCE",
  SELECT = "SELECT",
  CREDENTIAL = "CREDENTIAL",
  NUMBER = "NUMBER",
  BOOLEAN = "BOOLEAN",
  TEXTAREA = "TEXTAREA",
  JSON = "JSON",
}

export interface TaskParam {
  name: string;
  type: TaskParamType;
  helperText?: string;
  required?: boolean;
  hideHandle?: boolean;
  value?: string;
  [key: string]: any;
}
